easy_admin:
  user:
    display_name: true
    display_avatar: false
  design:
    assets:
      js:
        - 'https://unpkg.com/stackedit-js@1.0.7/docs/lib/stackedit.min.js'
        - 'js/custom_backend.js'
  entities:
    Article:
      class: App\Entity\Article
      list:
        fields:
          - 'id'
          - 'title'
          - 'text'
          - 'updatedAt'
          - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
      # ...
      show:
        fields:
          - 'id'
          - 'title'
          - 'text'
          - 'updatedAt'
          - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
      form:
        fields:
          - 'title'
          - { property: 'text', type: 'textarea', css_class: 'js-markdown-input' }
#          - { property: 'tags', type: 'collection', type_options: { entry_type: 'App\Form\TagType', allow_delete: true, allow_add: true, by_reference: false } }
          - { property: 'tags', type: 'entity', type_options: {class: 'App\Entity\Tag', by_reference: false, multiple: true } }
          - { property: 'imageFile', type: 'vich_image' }
